-- =====================================================================
-- 국가(ISO 3166-1) 시드 데이터  [Spring Boot 시딩용]
-- 출처: ISO 3166-1 (alpha-2/alpha-3/numeric, 영문명) + 한글 표기명
-- 범위: 주권국 + 속령·자치지역 전체 250개
-- 대륙(continent): region 기준, Americas는 subregion으로 남/북 분리
--   (중앙아메리카·카리브 → NORTH_AMERICA)
--
-- 사전 설정(application.properties):
--   spring.jpa.defer-datasource-initialization=true
--   spring.sql.init.mode=always
--   * 기본 data.sql만 자동 실행됨. 별도 파일로 둘 경우:
--     spring.sql.init.data-locations=classpath:data.sql,classpath:data-country.sql
--
-- 참고용 DDL:
-- CREATE TABLE country (
--     code         VARCHAR(2)  PRIMARY KEY,  -- ISO 3166-1 alpha-2
--     alpha3       VARCHAR(3)  NOT NULL,     -- alpha-3
--     numeric_code VARCHAR(3),               -- ISO numeric (선행 0 보존)
--     name_ko      VARCHAR(80) NOT NULL,
--     name_en      VARCHAR(80) NOT NULL,
--     continent    VARCHAR(20) NOT NULL      -- ASIA|EUROPE|AFRICA|NORTH_AMERICA|SOUTH_AMERICA|OCEANIA|ANTARCTICA
-- );
-- =====================================================================

INSERT INTO country (code, alpha3, numeric_code, name_ko, name_en, continent) VALUES
  ('DZ', 'DZA', '012', '알제리', 'Algeria', 'AFRICA'),
  ('AO', 'AGO', '024', '앙골라', 'Angola', 'AFRICA'),
  ('BJ', 'BEN', '204', '베냉', 'Benin', 'AFRICA'),
  ('BW', 'BWA', '072', '보츠와나', 'Botswana', 'AFRICA'),
  ('IO', 'IOT', '086', '인도', 'British Indian Ocean Territory', 'AFRICA'),
  ('BF', 'BFA', '854', '부르키나파소', 'Burkina Faso', 'AFRICA'),
  ('BI', 'BDI', '108', '부룬디', 'Burundi', 'AFRICA'),
  ('CM', 'CMR', '120', '카메룬', 'Cameroon', 'AFRICA'),
  ('CV', 'CPV', '132', '카보베르데', 'Cape Verde', 'AFRICA'),
  ('CF', 'CAF', '140', '중앙아프리카 공화국', 'Central African Republic', 'AFRICA'),
  ('TD', 'TCD', '148', '차드', 'Chad', 'AFRICA'),
  ('KM', 'COM', '174', '코모로', 'Comoros', 'AFRICA'),
  ('CG', 'COG', '178', '콩고', 'Congo', 'AFRICA'),
  ('CD', 'COD', '180', '콩고 민주 공화국', 'DR Congo', 'AFRICA'),
  ('DJ', 'DJI', '262', '지부티', 'Djibouti', 'AFRICA'),
  ('EG', 'EGY', '818', '이집트', 'Egypt', 'AFRICA'),
  ('GQ', 'GNQ', '226', '적도 기니', 'Equatorial Guinea', 'AFRICA'),
  ('ER', 'ERI', '232', '에리트레아', 'Eritrea', 'AFRICA'),
  ('SZ', 'SWZ', '748', '에스와티니', 'Eswatini', 'AFRICA'),
  ('ET', 'ETH', '231', '에티오피아', 'Ethiopia', 'AFRICA'),
  ('GA', 'GAB', '266', '가봉', 'Gabon', 'AFRICA'),
  ('GM', 'GMB', '270', '감비아', 'Gambia', 'AFRICA'),
  ('GH', 'GHA', '288', '가나', 'Ghana', 'AFRICA'),
  ('GN', 'GIN', '324', '기니', 'Guinea', 'AFRICA'),
  ('GW', 'GNB', '624', '기니비사우', 'Guinea-Bissau', 'AFRICA'),
  ('CI', 'CIV', '384', '코트디부아르', 'Ivory Coast', 'AFRICA'),
  ('KE', 'KEN', '404', '케냐', 'Kenya', 'AFRICA'),
  ('LS', 'LSO', '426', '레소토', 'Lesotho', 'AFRICA'),
  ('LR', 'LBR', '430', '라이베리아', 'Liberia', 'AFRICA'),
  ('LY', 'LBY', '434', '리비아', 'Libya', 'AFRICA'),
  ('MG', 'MDG', '450', '마다가스카르', 'Madagascar', 'AFRICA'),
  ('MW', 'MWI', '454', '말라위', 'Malawi', 'AFRICA'),
  ('ML', 'MLI', '466', '말리', 'Mali', 'AFRICA'),
  ('MR', 'MRT', '478', '모리타니', 'Mauritania', 'AFRICA'),
  ('MU', 'MUS', '480', '모리셔스', 'Mauritius', 'AFRICA'),
  ('YT', 'MYT', '175', '마요트', 'Mayotte', 'AFRICA'),
  ('MA', 'MAR', '504', '모로코', 'Morocco', 'AFRICA'),
  ('MZ', 'MOZ', '508', '모잠비크', 'Mozambique', 'AFRICA'),
  ('NA', 'NAM', '516', '나미비아', 'Namibia', 'AFRICA'),
  ('NE', 'NER', '562', '니제르', 'Niger', 'AFRICA'),
  ('NG', 'NGA', '566', '나이지리아', 'Nigeria', 'AFRICA'),
  ('RW', 'RWA', '646', '르완다', 'Rwanda', 'AFRICA'),
  ('RE', 'REU', '638', '레위니옹', 'Réunion', 'AFRICA'),
  ('SH', 'SHN', '654', '세인트헬레나', 'Saint Helena, Ascension and Tristan da Cunha', 'AFRICA'),
  ('SN', 'SEN', '686', '세네갈', 'Senegal', 'AFRICA'),
  ('SC', 'SYC', '690', '세이셸', 'Seychelles', 'AFRICA'),
  ('SL', 'SLE', '694', '시에라리온', 'Sierra Leone', 'AFRICA'),
  ('SO', 'SOM', '706', '소말리아', 'Somalia', 'AFRICA'),
  ('ZA', 'ZAF', '710', '남아프리카', 'South Africa', 'AFRICA'),
  ('SS', 'SSD', '728', '남수단', 'South Sudan', 'AFRICA'),
  ('SD', 'SDN', '729', '수단', 'Sudan', 'AFRICA'),
  ('ST', 'STP', '678', '상투메 프린시페', 'São Tomé and Príncipe', 'AFRICA'),
  ('TZ', 'TZA', '834', '탄자니아', 'Tanzania', 'AFRICA'),
  ('TG', 'TGO', '768', '토고', 'Togo', 'AFRICA'),
  ('TN', 'TUN', '788', '튀니지', 'Tunisia', 'AFRICA'),
  ('UG', 'UGA', '800', '우간다', 'Uganda', 'AFRICA'),
  ('EH', 'ESH', '732', '서사하라', 'Western Sahara', 'AFRICA'),
  ('ZM', 'ZMB', '894', '잠비아', 'Zambia', 'AFRICA'),
  ('ZW', 'ZWE', '716', '짐바브웨', 'Zimbabwe', 'AFRICA'),
  ('AQ', 'ATA', '010', '남극', 'Antarctica', 'ANTARCTICA'),
  ('BV', 'BVT', '074', '부베 섬', 'Bouvet Island', 'ANTARCTICA'),
  ('TF', 'ATF', '260', '프랑스령 남부와 남극 지역', 'French Southern and Antarctic Lands', 'ANTARCTICA'),
  ('HM', 'HMD', '334', '허드 맥도널드 제도', 'Heard Island and McDonald Islands', 'ANTARCTICA'),
  ('GS', 'SGS', '239', '조지아', 'South Georgia', 'ANTARCTICA'),
  ('AF', 'AFG', '004', '아프가니스탄', 'Afghanistan', 'ASIA'),
  ('AM', 'ARM', '051', '아르메니아', 'Armenia', 'ASIA'),
  ('AZ', 'AZE', '031', '아제르바이잔', 'Azerbaijan', 'ASIA'),
  ('BH', 'BHR', '048', '바레인', 'Bahrain', 'ASIA'),
  ('BD', 'BGD', '050', '방글라데시', 'Bangladesh', 'ASIA'),
  ('BT', 'BTN', '064', '부탄', 'Bhutan', 'ASIA'),
  ('BN', 'BRN', '096', '브루나이', 'Brunei', 'ASIA'),
  ('KH', 'KHM', '116', '캄보디아', 'Cambodia', 'ASIA'),
  ('CN', 'CHN', '156', '중국', 'China', 'ASIA'),
  ('GE', 'GEO', '268', '조지아', 'Georgia', 'ASIA'),
  ('HK', 'HKG', '344', '홍콩', 'Hong Kong', 'ASIA'),
  ('IN', 'IND', '356', '인도', 'India', 'ASIA'),
  ('ID', 'IDN', '360', '인도네시아', 'Indonesia', 'ASIA'),
  ('IR', 'IRN', '364', '이란', 'Iran', 'ASIA'),
  ('IQ', 'IRQ', '368', '이라크', 'Iraq', 'ASIA'),
  ('IL', 'ISR', '376', '이스라엘', 'Israel', 'ASIA'),
  ('JP', 'JPN', '392', '일본', 'Japan', 'ASIA'),
  ('JO', 'JOR', '400', '요르단', 'Jordan', 'ASIA'),
  ('KZ', 'KAZ', '398', '카자흐스탄', 'Kazakhstan', 'ASIA'),
  ('KW', 'KWT', '414', '쿠웨이트', 'Kuwait', 'ASIA'),
  ('KG', 'KGZ', '417', '키르기스스탄', 'Kyrgyzstan', 'ASIA'),
  ('LA', 'LAO', '418', '라오스', 'Laos', 'ASIA'),
  ('LB', 'LBN', '422', '레바논', 'Lebanon', 'ASIA'),
  ('MO', 'MAC', '446', '마카오', 'Macau', 'ASIA'),
  ('MY', 'MYS', '458', '말레이시아', 'Malaysia', 'ASIA'),
  ('MV', 'MDV', '462', '몰디브', 'Maldives', 'ASIA'),
  ('MN', 'MNG', '496', '몽골국', 'Mongolia', 'ASIA'),
  ('MM', 'MMR', '104', '미얀마', 'Myanmar', 'ASIA'),
  ('NP', 'NPL', '524', '네팔', 'Nepal', 'ASIA'),
  ('KP', 'PRK', '408', '조선', 'North Korea', 'ASIA'),
  ('OM', 'OMN', '512', '오만', 'Oman', 'ASIA'),
  ('PK', 'PAK', '586', '파키스탄', 'Pakistan', 'ASIA'),
  ('PS', 'PSE', '275', '팔레스타인', 'Palestine', 'ASIA'),
  ('PH', 'PHL', '608', '필리핀', 'Philippines', 'ASIA'),
  ('QA', 'QAT', '634', '카타르', 'Qatar', 'ASIA'),
  ('SA', 'SAU', '682', '사우디아라비아', 'Saudi Arabia', 'ASIA'),
  ('SG', 'SGP', '702', '싱가포르', 'Singapore', 'ASIA'),
  ('KR', 'KOR', '410', '한국', 'South Korea', 'ASIA'),
  ('LK', 'LKA', '144', '스리랑카', 'Sri Lanka', 'ASIA'),
  ('SY', 'SYR', '760', '시리아', 'Syria', 'ASIA'),
  ('TW', 'TWN', '158', '대만', 'Taiwan', 'ASIA'),
  ('TJ', 'TJK', '762', '타지키스탄', 'Tajikistan', 'ASIA'),
  ('TH', 'THA', '764', '태국', 'Thailand', 'ASIA'),
  ('TL', 'TLS', '626', '동티모르', 'Timor-Leste', 'ASIA'),
  ('TM', 'TKM', '795', '투르크메니스탄', 'Turkmenistan', 'ASIA'),
  ('TR', 'TUR', '792', '터키', 'Türkiye', 'ASIA'),
  ('AE', 'ARE', '784', '아랍에미리트', 'United Arab Emirates', 'ASIA'),
  ('UZ', 'UZB', '860', '우즈베키스탄', 'Uzbekistan', 'ASIA'),
  ('VN', 'VNM', '704', '베트남', 'Vietnam', 'ASIA'),
  ('YE', 'YEM', '887', '예멘', 'Yemen', 'ASIA'),
  ('AL', 'ALB', '008', '알바니아', 'Albania', 'EUROPE'),
  ('AD', 'AND', '020', '안도라', 'Andorra', 'EUROPE'),
  ('AT', 'AUT', '040', '오스트리아', 'Austria', 'EUROPE'),
  ('BY', 'BLR', '112', '벨라루스', 'Belarus', 'EUROPE'),
  ('BE', 'BEL', '056', '벨기에', 'Belgium', 'EUROPE'),
  ('BA', 'BIH', '070', '보스니아 헤르체고비나', 'Bosnia and Herzegovina', 'EUROPE'),
  ('BG', 'BGR', '100', '불가리아', 'Bulgaria', 'EUROPE'),
  ('HR', 'HRV', '191', '크로아티아', 'Croatia', 'EUROPE'),
  ('CY', 'CYP', '196', '키프로스', 'Cyprus', 'EUROPE'),
  ('CZ', 'CZE', '203', '체코', 'Czechia', 'EUROPE'),
  ('DK', 'DNK', '208', '덴마크', 'Denmark', 'EUROPE'),
  ('EE', 'EST', '233', '에스토니아', 'Estonia', 'EUROPE'),
  ('FO', 'FRO', '234', '페로 제도', 'Faroe Islands', 'EUROPE'),
  ('FI', 'FIN', '246', '핀란드', 'Finland', 'EUROPE'),
  ('FR', 'FRA', '250', '프랑스', 'France', 'EUROPE'),
  ('DE', 'DEU', '276', '독일', 'Germany', 'EUROPE'),
  ('GI', 'GIB', '292', '지브롤터', 'Gibraltar', 'EUROPE'),
  ('GR', 'GRC', '300', '그리스', 'Greece', 'EUROPE'),
  ('GG', 'GGY', '831', '건지 섬', 'Guernsey', 'EUROPE'),
  ('HU', 'HUN', '348', '헝가리', 'Hungary', 'EUROPE'),
  ('IS', 'ISL', '352', '아이슬란드', 'Iceland', 'EUROPE'),
  ('IE', 'IRL', '372', '아일랜드', 'Ireland', 'EUROPE'),
  ('IM', 'IMN', '833', '맨섬', 'Isle of Man', 'EUROPE'),
  ('IT', 'ITA', '380', '이탈리아', 'Italy', 'EUROPE'),
  ('JE', 'JEY', '832', '저지 섬', 'Jersey', 'EUROPE'),
  ('XK', 'UNK', NULL, '코소보', 'Kosovo', 'EUROPE'),
  ('LV', 'LVA', '428', '라트비아', 'Latvia', 'EUROPE'),
  ('LI', 'LIE', '438', '리히텐슈타인', 'Liechtenstein', 'EUROPE'),
  ('LT', 'LTU', '440', '리투아니아', 'Lithuania', 'EUROPE'),
  ('LU', 'LUX', '442', '룩셈부르크', 'Luxembourg', 'EUROPE'),
  ('MT', 'MLT', '470', '몰타', 'Malta', 'EUROPE'),
  ('MD', 'MDA', '498', '몰도바', 'Moldova', 'EUROPE'),
  ('MC', 'MCO', '492', '모나코', 'Monaco', 'EUROPE'),
  ('ME', 'MNE', '499', '몬테네그로', 'Montenegro', 'EUROPE'),
  ('NL', 'NLD', '528', '네덜란드', 'Netherlands', 'EUROPE'),
  ('MK', 'MKD', '807', '북마케도니아', 'North Macedonia', 'EUROPE'),
  ('NO', 'NOR', '578', '노르웨이', 'Norway', 'EUROPE'),
  ('PL', 'POL', '616', '폴란드', 'Poland', 'EUROPE'),
  ('PT', 'PRT', '620', '포르투갈', 'Portugal', 'EUROPE'),
  ('RO', 'ROU', '642', '루마니아', 'Romania', 'EUROPE'),
  ('RU', 'RUS', '643', '러시아', 'Russia', 'EUROPE'),
  ('SM', 'SMR', '674', '산마리노', 'San Marino', 'EUROPE'),
  ('RS', 'SRB', '688', '세르비아', 'Serbia', 'EUROPE'),
  ('SK', 'SVK', '703', '슬로바키아', 'Slovakia', 'EUROPE'),
  ('SI', 'SVN', '705', '슬로베니아', 'Slovenia', 'EUROPE'),
  ('ES', 'ESP', '724', '스페인', 'Spain', 'EUROPE'),
  ('SJ', 'SJM', '744', '스발바르 얀마옌 제도', 'Svalbard and Jan Mayen', 'EUROPE'),
  ('SE', 'SWE', '752', '스웨덴', 'Sweden', 'EUROPE'),
  ('CH', 'CHE', '756', '스위스', 'Switzerland', 'EUROPE'),
  ('UA', 'UKR', '804', '우크라이나', 'Ukraine', 'EUROPE'),
  ('GB', 'GBR', '826', '영국', 'United Kingdom', 'EUROPE'),
  ('VA', 'VAT', '336', '바티칸', 'Vatican City', 'EUROPE'),
  ('AX', 'ALA', '248', '올란드 제도', 'Åland Islands', 'EUROPE'),
  ('AI', 'AIA', '660', '앵귈라', 'Anguilla', 'NORTH_AMERICA'),
  ('AG', 'ATG', '028', '앤티가 바부다', 'Antigua and Barbuda', 'NORTH_AMERICA'),
  ('AW', 'ABW', '533', '아루바', 'Aruba', 'NORTH_AMERICA'),
  ('BS', 'BHS', '044', '바하마', 'Bahamas', 'NORTH_AMERICA'),
  ('BB', 'BRB', '052', '바베이도스', 'Barbados', 'NORTH_AMERICA'),
  ('BZ', 'BLZ', '084', '벨리즈', 'Belize', 'NORTH_AMERICA'),
  ('BM', 'BMU', '060', '버뮤다', 'Bermuda', 'NORTH_AMERICA'),
  ('VG', 'VGB', '092', '영국령 버진아일랜드', 'British Virgin Islands', 'NORTH_AMERICA'),
  ('CA', 'CAN', '124', '캐나다', 'Canada', 'NORTH_AMERICA'),
  ('BQ', 'BES', '535', '카리브 네덜란드', 'Caribbean Netherlands', 'NORTH_AMERICA'),
  ('KY', 'CYM', '136', '케이맨 제도', 'Cayman Islands', 'NORTH_AMERICA'),
  ('CR', 'CRI', '188', '코스타리카', 'Costa Rica', 'NORTH_AMERICA'),
  ('CU', 'CUB', '192', '쿠바', 'Cuba', 'NORTH_AMERICA'),
  ('CW', 'CUW', '531', '퀴라소', 'Curaçao', 'NORTH_AMERICA'),
  ('DM', 'DMA', '212', '도미니카 공화국', 'Dominica', 'NORTH_AMERICA'),
  ('DO', 'DOM', '214', '도미니카 공화국', 'Dominican Republic', 'NORTH_AMERICA'),
  ('SV', 'SLV', '222', '엘살바도르', 'El Salvador', 'NORTH_AMERICA'),
  ('GL', 'GRL', '304', '그린란드', 'Greenland', 'NORTH_AMERICA'),
  ('GD', 'GRD', '308', '그레나다', 'Grenada', 'NORTH_AMERICA'),
  ('GP', 'GLP', '312', '과들루프', 'Guadeloupe', 'NORTH_AMERICA'),
  ('GT', 'GTM', '320', '과테말라', 'Guatemala', 'NORTH_AMERICA'),
  ('HT', 'HTI', '332', '아이티', 'Haiti', 'NORTH_AMERICA'),
  ('HN', 'HND', '340', '온두라스', 'Honduras', 'NORTH_AMERICA'),
  ('JM', 'JAM', '388', '자메이카', 'Jamaica', 'NORTH_AMERICA'),
  ('MQ', 'MTQ', '474', '마르티니크', 'Martinique', 'NORTH_AMERICA'),
  ('MX', 'MEX', '484', '멕시코', 'Mexico', 'NORTH_AMERICA'),
  ('MS', 'MSR', '500', '몬트세랫', 'Montserrat', 'NORTH_AMERICA'),
  ('NI', 'NIC', '558', '니카라과', 'Nicaragua', 'NORTH_AMERICA'),
  ('PA', 'PAN', '591', '파나마', 'Panama', 'NORTH_AMERICA'),
  ('PR', 'PRI', '630', '푸에르토리코', 'Puerto Rico', 'NORTH_AMERICA'),
  ('BL', 'BLM', '652', '생바르텔레미', 'Saint Barthélemy', 'NORTH_AMERICA'),
  ('KN', 'KNA', '659', '세인트키츠 네비스', 'Saint Kitts and Nevis', 'NORTH_AMERICA'),
  ('LC', 'LCA', '662', '세인트루시아', 'Saint Lucia', 'NORTH_AMERICA'),
  ('MF', 'MAF', '663', '생마르탱', 'Saint Martin', 'NORTH_AMERICA'),
  ('PM', 'SPM', '666', '생피에르 미클롱', 'Saint Pierre and Miquelon', 'NORTH_AMERICA'),
  ('VC', 'VCT', '670', '세인트빈센트 그레나딘', 'Saint Vincent and the Grenadines', 'NORTH_AMERICA'),
  ('SX', 'SXM', '534', '신트마르턴', 'Sint Maarten', 'NORTH_AMERICA'),
  ('TT', 'TTO', '780', '트리니다드 토바고', 'Trinidad and Tobago', 'NORTH_AMERICA'),
  ('TC', 'TCA', '796', '터크스 케이커스 제도', 'Turks and Caicos Islands', 'NORTH_AMERICA'),
  ('US', 'USA', '840', '미국', 'United States', 'NORTH_AMERICA'),
  ('UM', 'UMI', '581', '미국령 군소 제도', 'United States Minor Outlying Islands', 'NORTH_AMERICA'),
  ('VI', 'VIR', '850', '미국령 버진아일랜드', 'United States Virgin Islands', 'NORTH_AMERICA'),
  ('AS', 'ASM', '016', '아메리칸사모아', 'American Samoa', 'OCEANIA'),
  ('AU', 'AUS', '036', '호주', 'Australia', 'OCEANIA'),
  ('CX', 'CXR', '162', '크리스마스 섬', 'Christmas Island', 'OCEANIA'),
  ('CC', 'CCK', '166', '코코스 제도', 'Cocos (Keeling) Islands', 'OCEANIA'),
  ('CK', 'COK', '184', '쿡 제도', 'Cook Islands', 'OCEANIA'),
  ('FJ', 'FJI', '242', '피지', 'Fiji', 'OCEANIA'),
  ('PF', 'PYF', '258', '프랑스령 폴리네시아', 'French Polynesia', 'OCEANIA'),
  ('GU', 'GUM', '316', '괌', 'Guam', 'OCEANIA'),
  ('KI', 'KIR', '296', '키리바시', 'Kiribati', 'OCEANIA'),
  ('MH', 'MHL', '584', '마셜 제도', 'Marshall Islands', 'OCEANIA'),
  ('FM', 'FSM', '583', '미크로네시아', 'Micronesia', 'OCEANIA'),
  ('NR', 'NRU', '520', '나우루', 'Nauru', 'OCEANIA'),
  ('NC', 'NCL', '540', '누벨칼레도니', 'New Caledonia', 'OCEANIA'),
  ('NZ', 'NZL', '554', '뉴질랜드', 'New Zealand', 'OCEANIA'),
  ('NU', 'NIU', '570', '니우에', 'Niue', 'OCEANIA'),
  ('NF', 'NFK', '574', '노퍽 섬', 'Norfolk Island', 'OCEANIA'),
  ('MP', 'MNP', '580', '북마리아나 제도', 'Northern Mariana Islands', 'OCEANIA'),
  ('PW', 'PLW', '585', '팔라우', 'Palau', 'OCEANIA'),
  ('PG', 'PNG', '598', '파푸아뉴기니', 'Papua New Guinea', 'OCEANIA'),
  ('PN', 'PCN', '612', '핏케언 제도', 'Pitcairn Islands', 'OCEANIA'),
  ('WS', 'WSM', '882', '사모아', 'Samoa', 'OCEANIA'),
  ('SB', 'SLB', '090', '솔로몬 제도', 'Solomon Islands', 'OCEANIA'),
  ('TK', 'TKL', '772', '토켈라우', 'Tokelau', 'OCEANIA'),
  ('TO', 'TON', '776', '통가', 'Tonga', 'OCEANIA'),
  ('TV', 'TUV', '798', '투발루', 'Tuvalu', 'OCEANIA'),
  ('VU', 'VUT', '548', '바누아투', 'Vanuatu', 'OCEANIA'),
  ('WF', 'WLF', '876', '왈리스 퓌튀나', 'Wallis and Futuna', 'OCEANIA'),
  ('AR', 'ARG', '032', '아르헨티나', 'Argentina', 'SOUTH_AMERICA'),
  ('BO', 'BOL', '068', '볼리비아', 'Bolivia', 'SOUTH_AMERICA'),
  ('BR', 'BRA', '076', '브라질', 'Brazil', 'SOUTH_AMERICA'),
  ('CL', 'CHL', '152', '칠레', 'Chile', 'SOUTH_AMERICA'),
  ('CO', 'COL', '170', '콜롬비아', 'Colombia', 'SOUTH_AMERICA'),
  ('EC', 'ECU', '218', '에콰도르', 'Ecuador', 'SOUTH_AMERICA'),
  ('FK', 'FLK', '238', '포클랜드 제도', 'Falkland Islands', 'SOUTH_AMERICA'),
  ('GF', 'GUF', '254', '프랑스령 기아나', 'French Guiana', 'SOUTH_AMERICA'),
  ('GY', 'GUY', '328', '가이아나', 'Guyana', 'SOUTH_AMERICA'),
  ('PY', 'PRY', '600', '파라과이', 'Paraguay', 'SOUTH_AMERICA'),
  ('PE', 'PER', '604', '페루', 'Peru', 'SOUTH_AMERICA'),
  ('SR', 'SUR', '740', '수리남', 'Suriname', 'SOUTH_AMERICA'),
  ('UY', 'URY', '858', '우루과이', 'Uruguay', 'SOUTH_AMERICA'),
  ('VE', 'VEN', '862', '베네수엘라', 'Venezuela', 'SOUTH_AMERICA')
ON CONFLICT (code) DO NOTHING;
